export const data = [
    {
        'Cat': 'tv', 
        'id': '1',
        'Brand': 'Samsung', 
        'Model': '85-inch Class QN85D 4K Neo QLED Smart TV', 
        'Screen Size': '85 Inches',
        'Display Technology': 'QLED',
        'Resolution': '4K',
        'images': ['samsung-qn85d-tv01.avif', 'samsung-qn85d-tv02.avif', 'samsung-qn85d-tv03.avif', 'samsung-qn85d-tv04.avif'],
    },
    {
        'Cat': 'tv', 
        'id': '2',
        'Brand': 'Samsung', 
        'Model': '65-inch Class Q60D 4K Smart TV', 
        'Screen Size': '65 Inches',
        'Display Technology': 'QLED',
        'Resolution': '4K',
        'images': ['samsung-q60d-tv01.avif', 'samsung-q60d-tv02.avif', 'samsung-q60d-tv03.webp', 'samsung-q60d-tv04.webp'],
    },
    {
        'Cat': 'tv', 
        'id': '3',
        'Brand': 'LG', 
        'Model': '55-inch Class QNED 4K UHD Smart TV', 
        'Screen Size': '55 Inches',
        'Display Technology': 'LED',
        'Resolution': '4K Ultra HD',
        'images': ['lg-55qned-tv01.png', 'lg-55qned-tv02.png', 'lg-55qned-tv03.png'],
    },
    {
        'Cat': 'tv', 
        'id': '4',
        'Brand': 'Xiaomi', 
        'Model': 'A2 50-inch HD', 
        'Screen Size': '50 Inches',
        'Display Technology': 'LED',
        'Resolution': '4K',
        'images': ['xiaomi-a2-50-tv01.png', 'xiaomi-a2-50-tv02.png', 'xiaomi-a2-50-tv03.png', 'xiaomi-a2-50-tv04.jpg'],
    },
    {
        'Cat': 'phone', 
        'id': '1',
        'Brand': 'Samsung', 
        'Model': 'Galaxy S24 Ultra', 
        'OS': 'Android 14',
        'RAM': '12GB',
        'Storage': '256GB/512GB/1TB',
        'Rear Camera': '200MP + 50MP + 12MP + 10MP',
        'Front Camera': '12MP',
        'images': ['samsung-galaxy-s24-ultra-pic01.jpg', 'samsung-galaxy-s24-ultra-pic03.jpg', 'samsung-galaxy-s24-ultra-pic04.jpg'],
    },
    {
        'Cat': 'phone', 
        'id': '2',
        'Brand': 'Apple', 
        'Model': 'iPhone 15 Pro', 
        'OS': 'IOS 17',
        'RAM': '8GB',
        'Storage': '128GB/256GB/512GB/1TB',
        'Rear Camera': '48MP + 12MP + 12MP',
        'Front Camera': '12MP',
        'images': ['apple-iphone-15-pro-pic01.jpg', 'apple-iphone-15-pro-pic02.jpg', 'apple-iphone-15-pro-pic03.jpg', 'apple-iphone-15-pro-pic04.jpg'],
    },
    {
        'Cat': 'phone', 
        'id': '3',
        'Brand': 'Samsung', 
        'Model': 'Galaxy Z Fold6', 
        'OS': 'Android 14',
        'RAM': '12GB',
        'Storage': '256GB/512GB/1TB',
        'Rear Camera': '50MP + 12MP + 10MP',
        'Front Camera': '-',
        'images': ['samsung-galaxy-z-fold6-pic01.webp', 'samsung-galaxy-z-fold6-pic02.webp', 'samsung-galaxy-z-fold6-pic03.webp'],
    },
    {
        'Cat': 'laptop', 
        'id': '1',
        'Brand': 'ASUS', 
        'Model': 'ROG Strix G16', 
        'Screen Size': '16 Inches',
        'CPU': 'Intel Core i9',
        'GPU': 'GeForce RTX 4080 / 12GB',
        'RAM': '16GB',
        'Hard': '1TB',
        'images': ['asus-rog-strix-g16-pic01.jpg', 'asus-rog-strix-g16-pic02.jpg', 'asus-rog-strix-g16-pic03.jpg'],
    },
    {
        'Cat': 'laptop', 
        'id': '2',
        'Brand': 'ASUS', 
        'Model': 'Vivobook Go 15', 
        'Screen Size': '15.6 Inches',
        'CPU': 'AMD Ryzen 5',
        'GPU': 'Radeon 610M / 8GB',
        'RAM': '8GB',
        'Hard': '512GB',
        'images': ['asus-vivobook-go-15-pic01.jpg', 'asus-vivobook-go-15-pic02.jpg', 'asus-vivobook-go-15-pic03.jpg'],
    },
    {
        'Cat': 'laptop', 
        'id': '3',
        'Brand': 'ASUS', 
        'Model': 'TUF Gaming A16', 
        'Screen Size': '16 Inches',
        'CPU': 'AMD Ryzen 7',
        'GPU': 'Radeon RX 7600S / 8GB',
        'RAM': '16GB',
        'Hard': '1TB',
        'images': ['asus-tuf-gaming-a16-pic01.jpg', 'asus-tuf-gaming-a16-pic02.jpg', 'asus-tuf-gaming-a16-pic03.jpg', 'asus-tuf-gaming-a16-pic04.jpg'],
    },
]